// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4b1aTSSy4SQK70frvxSgDQu195cs2ZIg',
    appId: '1:41260928318:web:e37d124581b4590e11706f',
    messagingSenderId: '41260928318',
    projectId: 'hotspot-ece88',
    authDomain: 'hotspot-ece88.firebaseapp.com',
    storageBucket: 'hotspot-ece88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpRuYcytKtHlOiUx8w_IEg6-HSPEkwCaQ',
    appId: '1:41260928318:android:bf95eb55f11e363c11706f',
    messagingSenderId: '41260928318',
    projectId: 'hotspot-ece88',
    storageBucket: 'hotspot-ece88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMEQS5rluTshJk086ojxSIdLZsDf7M0O4',
    appId: '1:41260928318:ios:00d54cd2303f2f4111706f',
    messagingSenderId: '41260928318',
    projectId: 'hotspot-ece88',
    storageBucket: 'hotspot-ece88.firebasestorage.app',
    iosBundleId: 'com.example.hotspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMEQS5rluTshJk086ojxSIdLZsDf7M0O4',
    appId: '1:41260928318:ios:00d54cd2303f2f4111706f',
    messagingSenderId: '41260928318',
    projectId: 'hotspot-ece88',
    storageBucket: 'hotspot-ece88.firebasestorage.app',
    iosBundleId: 'com.example.hotspot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4b1aTSSy4SQK70frvxSgDQu195cs2ZIg',
    appId: '1:41260928318:web:7ada755c097dcc5311706f',
    messagingSenderId: '41260928318',
    projectId: 'hotspot-ece88',
    authDomain: 'hotspot-ece88.firebaseapp.com',
    storageBucket: 'hotspot-ece88.firebasestorage.app',
  );
}
